Update 3-redirection

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,13 +1,9 @@
 #!/usr/bin/env bash
 # This script configures Nginx to redirect /redirect_me to another page with a "301 Moved Permanently"
 
-# Ensure Nginx is installed
-if ! command -v nginx &> /dev/null
-then
-	    # Install Nginx if not installed
-	        sudo apt-get update
-		    sudo apt-get install -y nginx
-fi
+# Install Nginx
+sudo apt-get update
+sudo apt-get install -y nginx
 
 # Configure Nginx for redirection
 sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
@@ -36,17 +32,8 @@ sudo kill -HUP $(cat /var/run/nginx.pid)
 # Check if Nginx is running
 if pgrep -x "nginx" >/dev/null
 then
-	    echo "Nginx is running."
-    else
-	        echo "Error: Nginx is not running."
-		    exit 1
+    echo "Nginx is running."
+else
+    echo "Error: Nginx is not running."
+    exit 1
 fi
-
-# Test redirection with curl
-response=$(curl -sI http://127.0.0.1/redirect_me/)
-if [[ $response == *"301 Moved Permanently"* ]]; then
-	    echo "Nginx redirection is configured successfully."
-    else
-	        echo "Error: Nginx redirection configuration failed."
-fi
-
